### ISSUE TITLE
Suitcase does not handle accented upper case correctly

### ISSUE THREAD

**Issue by pkmarmor** [alondmnt/joplin-plugin-suitcase#2]
**Use case:**

I want to change ÉCOLE ANGLO-NÉERLANDAISE to Title Case.  Select "ÉCOLE ANGLO-NÉERLANDAISE" and choose "Title Case" from the Capitalization menu.

**Expected result:**

École Anglo-Néerlandaise

**Actual result:**

- Select "ÉCOLE ANGLO-NÉERLANDAISE" and choose "Title Case" - nothing is changed
- Select "ÉCOLE ANGLO-NÉERLANDAISE" and choose "lower case" - get correct result "école anglo-néerlandaise"
- Select "école anglo-néerlandaise" and choose "Title Case" - get incorrect result "éCole Anglo-Néerlandaise"

**Comment by pkmarmor** [comment]
In general, there seems to be a problem converting from UPPER CASE to Title Case.  The string "HANS EWORTH (ACTIVE ANTWERP 1540-1573/4 LONDON)" won't convert to Title Case, but it will convert to lower case and the new lower case will convert to Title Case.

**Comment by alondmnt** [comment]
Hi!

>it will convert to lower case and the new lower case will convert to Title Case.

Indeed, this is how it works.

>Select "école anglo-néerlandaise" and choose "Title Case" - get incorrect result "éCole Anglo-Néerlandaise"

I'll check this, thanks for the feedback.

**Comment by alondmnt** [comment]
Please check v0.3.1
